name: PR_OPENED TG ALERT

on:
  pull_request:
    types: [opened]
    branches:
    - main
    - test

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ALERT_CHANNEL }}
          token: ${{ secrets.BOT }}
          message: FRONTEND - ${{ github.actor }} открыл ${{ github.event_name }} ветки ${{ github.head_ref }} в ${{ github.base_ref }}
